jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1 -- Build Docker image
      - name: Build Docker image
        run: docker build -t playwright-tests:latest .

      # Step 2 -- Login to registry
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | 
             docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3 -- Push to registry
      - name: Push to registry
        run: |
          docker tag playwright-tests:latest \
            ghcr.io/knilagiri9/playwright-tests:latest
          docker push ghcr.io/knilagiri9/playwright-tests:latest

      # Step 4 -- Deploy to K8s
      - name: Apply K8s configs
        run: |
          kubectl apply -f k8s/namespace.yml
          kubectl apply -f k8s/secret.yml
          kubectl apply -f k8s/test-job.yml

      # Step 5 -- Wait for tests to finish
      - name: Wait for job completion
        run: |
          kubectl wait --for=condition=complete \
            job/playwright-tests \
            -n playwright-tests \
            --timeout=300s

      # Step 6 -- Get test results
      - name: Get pod logs
        run: |
          kubectl logs \
            -l app=playwright-tests \
            -n playwright-tests